# https://github.com/xtoys/openwrt
#
# Description: Build OpenWrt DockerImages using GitHub Actions
#

name: Build DockerImage

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Firmware download url'
        required: true
        default: ''
      dir:
        description: 'Dockerfile directory'
        required: true
        default: 'docker'
      img:
        description: 'DockerImage Name'
        required: true
        default: 'openwrt'
      tag:
        description: 'DockerImage TagName'
        required: true
        default: 'latest'
      platform:
        description: 'DockerImage Platform'
        required: true
        default: 'linux/arm64'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download target firmware
        run: |
          cd ${{ github.event.inputs.dir }}
          wget ${{ github.event.inputs.url }} -O rootfs.tar.gz

      - name: Setup QEMU Simulator
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.event.inputs.dir }}
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.img }}:${{ github.event.inputs.tag }}